### ISSUE TITLE
README.md - Example connection-url not helpful

### ISSUE THREAD

**Issue by tfindlay-au** [marcelopaesrech/presto-oracle#1]
I just wanted to add a note that in the README.md you offer an example configuration.

The suggested URL format did not work for me:
connection-url=jdbc:oracle:thin://ip:port/database
When using this (replacing the IP, Port and Sevice Name) I received :
java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection

I had to add the AT symbol like so:
connection-url=jdbc:oracle:thin:@//ip:port/database

With this, I used ojdbc6 version 11.2.0.3 as per the pom.

**Comment by marcelopaesrech** [comment]
Hi @tfindlay-au,

I made a change in the docs.

Regards.
